require(devtools)
data(APa_map)
data(APb_map)
data(Sa_map)
data(Sb_map)
data(Sa_map)
data(Ha_map)
data(Hb_map)
data(CFC)
data(CSTmap)
use_data(APa_map,APb_map,Sa_map,Sb_map,Sc_map,Ha_map,Hb_map, CFC, CSTmap, pkg="sirad", internal = TRUE, overwrite = T)